FROM copr-base:latest

LABEL description="COPR Builder - RPM build worker"

RUN --mount=type=cache,target=/var/cache/dnf \
    dnf -y install \
        copr-builder \
        createrepo \
        fedora-packager \
        mock \
        mock-lvm \
        openssh-clients \
        openssh-server \
        rsync \
        yum-utils \
    && dnf clean all

COPY files/ /

RUN set -ex && \
    ssh-keygen -f /etc/ssh/ssh_host_rsa_key -N '' -q && \
    echo 'root:passwd' | chpasswd && \
    chmod 700 /root /root/.ssh && \
    touch /root/.ssh/authorized_keys && \
    chmod 600 /root/.ssh/authorized_keys && \
    echo 'config_opts["use_nspawn"] = False' >> /etc/mock/site-defaults.cfg

EXPOSE 22
ENTRYPOINT []
CMD ["/usr/sbin/sshd", "-D"]
