"""persistent attribute added for copr model

Revision ID: 1ae2302aa2e6
Revises: 4567fd34cfb6
Create Date: 2016-08-08 13:02:26.699654

"""

# revision identifiers, used by Alembic.
revision = '1ae2302aa2e6'
down_revision = '4567fd34cfb6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('copr', sa.Column('persistent', sa.Boolean(), server_default='0', nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('copr', 'persistent')
    ### end Alembic commands ###
