"""Add old_status to Package

Revision ID: 2add9a2c36d9
Revises: 573044986ee9
Create Date: 2016-02-24 02:51:35.808885

"""

# revision identifiers, used by Alembic.
revision = '2add9a2c36d9'
down_revision = '573044986ee9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('package', sa.Column('old_status', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('package', 'old_status')
    ### end Alembic commands ###
