"""Add proxy column to user table

Revision ID: 38ea34def9a
Revises: 4af9d157c4ea
Create Date: 2017-02-06 17:56:10.187111

"""

# revision identifiers, used by Alembic.
revision = '38ea34def9a'
down_revision = '4af9d157c4ea'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('proxy', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'proxy')
    ### end Alembic commands ###
