"""empty message

Revision ID: 3c3cce7a5fe0
Revises: 2fa80e062525
Create Date: 2013-01-22 09:42:39.037642

"""

# revision identifiers, used by Alembic.
revision = "3c3cce7a5fe0"
down_revision = "2fa80e062525"

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column("copr", sa.Column("description", sa.Text(), nullable=True))
    op.add_column("copr", sa.Column("instructions", sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("copr", "instructions")
    op.drop_column("copr", "description")
    ### end Alembic commands ###
