"""
Add Notification table

Revision ID: 86cb0360405d
Create Date: 2026-08-09 14:20:01.887507
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86cb0360405d'
down_revision = 'e31b4af2468c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('notification_type', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('seen_on', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('notification_user_seen_idx', 'notification', ['user_id', 'seen_on'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('notification_user_seen_idx', table_name='notification')
    op.drop_table('notification')
    # ### end Alembic commands ###
