"""added column Copr.build_enable_net

Revision ID: bd0dab2e478
Revises: 2df28d2d072f
Create Date: 2015-01-05 11:47:15.291386

"""

# revision identifiers, used by Alembic.
revision = 'bd0dab2e478'
down_revision = '2df28d2d072f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('copr', sa.Column('build_enable_net', sa.Boolean(), server_default='1', nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('copr', 'build_enable_net')
    ### end Alembic commands ###
