#! /bin/bash -x

diff_against=origin/main

case $GITHUB_EVENT_NAME in
push)
    diff_against=$1
    ;;
pull_request)
    diff_against=$2
    # Pull request event from a remote fork
    git config --global --add safe.directory '*'
    git config --global advice.detachedHead false
    ;;
*)
    echo >&2 "Unknown GITHUB_EVENT_NAME, diffing against $diff_against"
    ;;
esac

# Some debugging info
true "\$GITHUB_REF: $GITHUB_REF"
true "\$GITHUB_SHA: $GITHUB_SHA"
git rev-parse HEAD >&2
git rev-parse "$diff_against" >&2

echo -n "{"
echo -n '"package": ['
separator=""

dump_package_name() {
    echo -n "$separator\"$1\""
    separator=", "
}

git diff --name-status -C "$diff_against" --numstat | cut -f2 | sed 's|/.*||' \
| sort | uniq | while read -r line; do
    case $line in
        backend|frontend|cli|keygen|dist-git|messaging|rpmbuild|selinux)
            dump_package_name "copr-$line"
            ;;
        python)
            dump_package_name python-copr
            ;;
        common)
            dump_package_name python-copr-common
            ;;
    esac
done
echo "]}"
