#! /bin/bash -x

diff_against=origin/main

case $GITHUB_EVENT_NAME in
push)
    diff_against=$1
    ;;
pull_request)
    diff_against=$2
    # Pull request event from a remote fork
    git config --global --add safe.directory '*'
    git config --global advice.detachedHead false
    ;;
*)
    echo >&2 "Unknown GITHUB_EVENT_NAME, diffing against $diff_against"
    ;;
esac

# Some debugging info
true "\$GITHUB_REF: $GITHUB_REF"
true "\$GITHUB_SHA: $GITHUB_SHA"
git rev-parse HEAD >&2
git rev-parse "$diff_against" >&2

echo -n "{"
echo -n '"package": ['
separator=""

dump_package_name() {
    echo -n "$separator\"$1\""
    separator=", "
}

./releng/detect-changed-packages "$diff_against" | \
while read package; do
    dump_package_name "$package"
done
echo "]}"
