#!/usr/bin/sh

runuser -c "PYTHONUNBUFFERED=1 python3 /usr/bin/copr_prune_results.py &> /dev/null" - copr
runuser -c "PYTHONUNBUFFERED=1 python3 /usr/bin/copr_prune_srpms.py &> /dev/null" - copr

# Optional - Counting downloaded RPMs through Amazon CDN
# runuser -c "PYTHONUNBUFFERED=1 python3 /usr/bin/copr-aws-s3-hitcounter &> /dev/null" - copr
