---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql
type: Opaque
stringData:
  database-user: {{ .Values.postgres_user | quote }}
  database-password: {{ .Values.postgres_password | quote }}
  database-name: {{ .Values.postgres_database_name | quote }}

---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
spec:
  ports:
    - name: postgresql
      port: 5432
      targetPort: 5432
  selector:
    name: postgresql

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ ternary "12Gi" "1Gi" (eq .Values.deployment "prod") | quote }}

---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: postgresql
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    name: postgresql
  strategy:
    type: Recreate
    resources:
{{ toYaml .Values.resources.postgres.strategy | indent 6 }}
  template:
    metadata:
      labels:
        name: postgresql
        test: test-postgresql-tag
    spec:
      containers:
        - env:
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  key: database-user
                  name: postgresql
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: database-password
                  name: postgresql
            - name: POSTGRESQL_DATABASE
              valueFrom:
                secretKeyRef:
                  key: database-name
                  name: postgresql
          image: {{ .Values.postgresql_image | quote }}
          imagePullPolicy: IfNotPresent
          startupProbe:
            exec:
              command:
                - /usr/libexec/check-container
            failureThreshold: 30
            periodSeconds: 2
          livenessProbe:
            exec:
              command:
                - /usr/libexec/check-container
                - --live
            initialDelaySeconds: 120
            timeoutSeconds: 10
          name: postgresql
          ports:
            - containerPort: 5432
              protocol: TCP
          readinessProbe:
            exec:
              command:
                - /usr/libexec/check-container
            initialDelaySeconds: 5
            timeoutSeconds: 1
          resources:
{{ toYaml .Values.resources.postgres.app | indent 12 }}
          volumeMounts:
            - mountPath: /var/lib/pgsql/data
              name: postgresql-data
      restartPolicy: Always
      volumes:
        - name: postgresql-data
          persistentVolumeClaim:
            claimName: postgresql

  triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
          - postgresql
        from:
          kind: ImageStreamTag
          name: postgresql:12-el8
          namespace: openshift
      type: ImageChange
    - type: ConfigChange
