FROM registry.fedoraproject.org/fedora:43
LABEL maintainer="copr-devel@lists.fedorahosted.org"
LABEL description="COPR Frontend - Web UI and API"

ARG ADDITIONAL_COPR_REPOSITORIES="@copr/copr-dev"

ENV TERM=linux
ENV LANG=en_US.UTF-8
ENV REDIS_HOST=redis

RUN set -ex ; \
    test -z "${ADDITIONAL_COPR_REPOSITORIES}" \
        || dnf -y install dnf-plugins-core \
        && for repo in $ADDITIONAL_COPR_REPOSITORIES ; do dnf -y copr enable $repo; done ; \
    dnf -y update && \
    dnf -y install htop \
                   make \
                   which \
                   wget \
                   vim \
                   yum \
                   sudo \
                   python3-alembic \
                   python3-anytree \
                   postgresql-server \
                   redis \
                   mock-core-configs \
                   findutils \
                   copr-frontend \
                   modulemd-tools \
                   python3-authlib \
    && dnf clean all

COPY files/ /

RUN sed -i 's/User apache/User copr-fe/g' /etc/httpd/conf/httpd.conf && \
    sed -i 's/Group apache/Group copr-fe/g' /etc/httpd/conf/httpd.conf && \
    sed -i 's/Listen 80/#Listen 80/g' /etc/httpd/conf/httpd.conf && \
    echo "PidFile /var/run/httpd/httpd.pid" >> /etc/httpd/conf/httpd.conf

RUN sed -i "s/REDIS_HOST = \"redis\"/REDIS_HOST = \"${REDIS_HOST}\"/g" /etc/copr/copr.conf

RUN chown -R copr-fe:root \
    /usr/share/copr \
    /var/log/copr-frontend \
    /etc/httpd/ \
    /var/run/httpd/ \
    /var/log/httpd/ && \
    chmod -R g+rwX \
    /usr/share/copr \
    /var/log/copr-frontend \
    /etc/httpd/ \
    /var/run/httpd/ \
    /var/log/httpd/

USER copr-fe

ENV PS1="[\u@\h \W]\$ "

EXPOSE 5000

CMD ["/entrypoint"]
