FROM registry.fedoraproject.org/fedora:43

ARG PULL_REQUEST_ID= \
    PULL_REQUEST_HEAD_SHA=

RUN set -ex ; \
    dnf -y update && \
    dnf -y copr enable @mock/mock && \
    dnf -y copr enable @copr/copr-dev && \
    dnf -y install \
        copr-builder \
        openssh-server \
        which \
    && dnf clean all

RUN set -x ; set -e ; test -n "$PULL_REQUEST_ID" || exit 0 ; \
    curl https://raw.githubusercontent.com/fedora-copr/copr/refs/heads/main/releng/install-copr-packages -o /usr/local/bin/install-copr-packages ; \
    chmod +x /usr/local/bin/install-copr-packages ; \
    install-copr-packages "@copr/copr-pull-requests:pr:$PULL_REQUEST_ID" "$PULL_REQUEST_HEAD_SHA" copr-rpmbuild

RUN ssh-keygen -f /etc/ssh/ssh_host_rsa_key -N '' -q

# allow ssh to root@localhost without password
RUN mkdir -p /root/.ssh && chmod 700 /root /root/.ssh
COPY key.pub /root/.ssh/authorized_keys
RUN chmod 600 /root/.ssh/authorized_keys

COPY self-signed-ca.crt /etc/pki/ca-trust/source/anchors/self-signed-ca.crt
RUN update-ca-trust

# install mockbuilder user, and allow ssh to it
RUN useradd mockbuilder && usermod -a -G mock mockbuilder
RUN mkdir -p /home/mockbuilder/.ssh \
    && chmod 700 /home/mockbuilder/.ssh \
    && cp /root/.ssh/authorized_keys /home/mockbuilder/.ssh \
    && chown -R mockbuilder:mockbuilder /home/mockbuilder/.ssh

COPY copr.ini /etc/dist-git-client/copr.ini
COPY main.ini /etc/copr-rpmbuild/main.ini

RUN set -x ; cd /etc/mock ; \
    for arch in aarch64 ppc64le s390x x86_64; do \
        for distro in epel-6 epel-7; do \
            test -f eol/$distro-$arch.cfg && ln -s eol/$distro-$arch.cfg $distro-$arch.cfg ; \
        done ; \
        for distro in epel-8 epel-9; do \
            test -f centos-stream+$distro-$arch.cfg && ln -s centos-stream+$distro-$arch.cfg $distro-$arch.cfg ; \
        done ; \
    done

CMD ["/usr/sbin/sshd", "-D"]
