FROM registry.fedoraproject.org/fedora:43
LABEL maintainer="copr-devel@lists.fedorahosted.org"
LABEL description="COPR Backend HTTPD - serves build results"

RUN dnf install -y nginx && dnf clean all

COPY files/nginx.conf /etc/nginx/conf.d/default.conf

RUN mkdir -p /var/lib/copr/public_html/results && \
    chown -R nginx:nginx /var/lib/copr

EXPOSE 5002

CMD ["nginx", "-g", "daemon off;"]
