---
- name: Prepare the testing machine for running Copr tests
  hosts: all
  user: "root"

  vars:
    host_with_secrets: "{{ ansible_host }}"
    ansible_python_interpreter: /usr/bin/python3

  roles:
    - credentials
    - ca-trust
    - resalloc
    - distgit
    - backend
    - frontend

  handlers:
    - name: restart httpd
      ansible.builtin.systemd_service:
        name: httpd
        state: restarted

  tasks:
    - name: pre-release copr packages
      community.general.copr:
        name: '@copr/copr-dev'

    - name: install packages needed when testing
      package:
        name:
          - git
        state: latest

    - name: print packit variable
      ansible.builtin.debug:
        msg: "$PACKIT_TARGET_SHA is '{{ lookup('ansible.builtin.env', 'PACKIT_TARGET_SHA') }}'"

    - name: print packit variable
      ansible.builtin.debug:
        msg: "$PACKIT_PR_ID is '{{ lookup('ansible.builtin.env', 'PACKIT_PR_ID') }}'"
