---
- name: Prepare the testing machine for running Copr tests
  hosts: all
  user: "root"

  vars:
    host_with_secrets: "{{ ansible_host }}"
    ansible_python_interpreter: /usr/bin/python3
    test_user: single-host-testing
    frontend_hostname: '{{ ansible_host | regex_replace("^root@", "") }}'
    backend_hostname: '{{ ansible_host | regex_replace("^root@", "") }}'
    distgit_hostname: '{{ ansible_host | regex_replace("^root@", "") }}'

  roles:
    - pre-release-packages
    - credentials
    - ca-trust
    - resalloc
    - distgit
    - backend
    - frontend
    - keygen
    - role: client
      vars:
        copr_username: "{{ test_user }}"

  handlers:
    - name: restart httpd
      ansible.builtin.systemd_service:
        name: httpd
        state: restarted
