---
- name: Prepare the testing machine for running Copr tests
  hosts: all
  user: "root"

  vars:
    host_with_secrets: "{{ ansible_host }}"
    ansible_python_interpreter: /usr/bin/python3
    test_user: single-host-testing

  roles:
    - pre-release-packages
    - credentials
    - ca-trust
    - resalloc
    - distgit
    - backend
    - frontend
    - keygen
    - role: client
      vars:
        copr_username: "{{ test_user }}"

  handlers:
    - name: restart httpd
      ansible.builtin.systemd_service:
        name: httpd
        state: restarted

  tasks:
    - name: create a testing project
      ansible.builtin.command: >
        sudo -i -u "{{ test_user }}"
        copr create foo --chroot fedora-rawhide-x86_64
