"""added unlisted_on_hp attribute for Copr

Revision ID: 1c61e5b88e45
Revises: 3b1ee8f6baaf
Create Date: 2016-06-16 08:30:46.559908

"""

# revision identifiers, used by Alembic.
revision = '1c61e5b88e45'
down_revision = '3b1ee8f6baaf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('copr', sa.Column('unlisted_on_hp', sa.Boolean(), nullable=False, server_default='f'))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('copr', 'unlisted_on_hp')
    ### end Alembic commands ###
