"""Add forked_from_id column

Revision ID: 22c5f7a954ce
Revises: 2add9a2c36d9
Create Date: 2016-02-29 13:52:59.175869

"""

# revision identifiers, used by Alembic.
revision = '22c5f7a954ce'
down_revision = '2add9a2c36d9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('copr', sa.Column('forked_from_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'copr', 'copr', ['forked_from_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('copr', 'forked_from_id')
    ### end Alembic commands ###
