"""added column comps_name to CoprChroot

Revision ID: 22fde92cb568
Revises: 4f6b48ec62ab
Create Date: 2015-08-18 12:28:49.816996

"""

# revision identifiers, used by Alembic.
revision = '22fde92cb568'
down_revision = '4f6b48ec62ab'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('copr_chroot', sa.Column('comps_name', sa.String(length=127), nullable=True))
    op.add_column('copr_chroot', sa.Column('comps_zlib', sa.LargeBinary(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('copr_chroot', 'comps_name')
    op.drop_column('copr_chroot', 'comps_zlib')
    ### end Alembic commands ###
