"""added column Build.enable_net

Revision ID: 2df28d2d072f
Revises: 1d5b5b1b27f9
Create Date: 2015-01-02 17:55:02.169421

"""

# revision identifiers, used by Alembic.
revision = '2df28d2d072f'
down_revision = '1d5b5b1b27f9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('build', sa.Column('enable_net', sa.Boolean(), server_default='0', nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('build', 'enable_net')
    ### end Alembic commands ###

