"""empty message

Revision ID: 3b4cfc666d14
Revises: 22fde92cb568
Create Date: 2015-08-31 17:17:52.396183

"""

# revision identifiers, used by Alembic.
revision = '3b4cfc666d14'
down_revision = '22fde92cb568'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('build', sa.Column('fail_type', sa.Integer(), default=0))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('build', 'fail_type')
    ### end Alembic commands ###
