"""added module_md_zlib and module_md_name to coprchroot

Revision ID: 4567fd34cfb6
Revises: 1ff696f006f1
Create Date: 2016-07-18 13:58:51.629188

"""

# revision identifiers, used by Alembic.
revision = '4567fd34cfb6'
down_revision = '1ff696f006f1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('copr_chroot', sa.Column('module_md_name', sa.String(length=127), nullable=True))
    op.add_column('copr_chroot', sa.Column('module_md_zlib', sa.LargeBinary(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('copr_chroot', 'module_md_zlib')
    op.drop_column('copr_chroot', 'module_md_name')
    ### end Alembic commands ###
