"""build packages and subpackages

Revision ID: 5055336e8c44
Revises: 20140423001
Create Date: 2014-07-15 10:12:21.875119

"""

# revision identifiers, used by Alembic.
revision = '5055336e8c44'
down_revision = '20140423001'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('build', sa.Column('pkg_version', sa.Text(), nullable=True))
    op.add_column('build', sa.Column('built_packages', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('build', 'built_packages')
    op.drop_column('build', 'pkg_version')
    ### end Alembic commands ###
