"""empty message

Revision ID: 573044986ee9
Revises: 4b57794e2b5
Create Date: 2015-11-26 12:36:59.729053

"""

# revision identifiers, used by Alembic.
revision = '573044986ee9'
down_revision = '4b57794e2b5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('copr', sa.Column('webhook_secret', sa.String(length=100), nullable=True))
    op.add_column('package', sa.Column('enable_net', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('package', sa.Column('webhook_rebuild', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('package', 'webhook_rebuild')
    op.drop_column('package', 'enable_net')
    op.drop_column('copr', 'webhook_secret')
    ### end Alembic commands ###
