copr-cli(1)
==========
:man source:  copr
:man manual:  COPR

NAME
----
copr-cli - command line interface for the Copr service


SYNOPSIS
--------
copr-cli [-h] [--version] {list,create,build} ...

DESCRIPTION
-----------

This command allows you to interact with the Copr service from the command line.

You need to generate an API key first (see the API KEY section below).

OPTIONS
-------

-h, --help::
show this help message and exit

--version::
show the program's version number and exit

ACTIONS
-------

list [username]::
List all the projects of the provided username. If no username is provided,
then your projects are listed.

create::
Create a new project.

delete::
Delete an entire project.

build::
Build packages for a specified project.

status::
Get the status of the build.

cancel::
Cancel a build of given id.

download-build::
Download a build to local directory.

modify::
Modify existing copr


`copr-cli create [options]`
~~~~~~~~~~~~~~~~~~~~~~~~~~~

usage: copr-cli create [-h] --chroot CHROOTS [--repo REPOS]
                       [--initial-pkgs URL_OF_INITIAL_PKGS]
                       [--description DESCRIPTION]
                       [--instructions INSTRUCTIONS]
                       name

--chroot::
Chroot to use for this project. Can be specified multiple times, but at least one must be present.

--repo::
Repository to add to this project. Can be specified multiple times.

--initial-pkgs::
List of packages to build in this new project. Can be specified multiple times.

--description::
Description of the project.

--instructions::
Instructions for the project.


`copr-cli build [options]`
~~~~~~~~~~~~~~~~~~~~~~~~~~

usage: copr-cli build [-h] [-r, --chroot CHROOTS] [--memory MEMORY] [--timeout TIMEOUT] [--nowait]
                      project pkg_url [pkg_url ...]

-r, --chroot::
If you don't need this build for all the project's chroots. You can use it several times for each chroot you need.

--memory::
Override memory for this build

--timeout::
Override timeout for this build

--nowait::
Don't wait for build completion

project::
The project build the package in. This can be a simple name of some of
your projects. Alternatively, you can specify it as username/project. This
way you can build into the project of another user provided you have the
permissions to do so.

pkg_url::
URL of the package to build. The package must be placed on a public web or
ftp server.


`copr-cli download-build [options]`
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

usage: copr-cli download-build [-h] [-d, --dest DESTINATION]
                               [-r, --chroot CHROOT]
                               build_id

build_id::
Download built packages for build identified by build_id.

-d, --dest::
Base directory to fetch files. Using `pwd` by default

-r, --chroot::
Fetch only selected chroots. Can be specified multiple times.\


`copr-cli modify [options]`
~~~~~~~~~~~~~~~~~~~~~~~~~~

usage: copr-cli modify [-h] [--repo REPOS]
                       [--description DESCRIPTION]
                       [--instructions INSTRUCTIONS]
                       [--disable_createrepo DISABLE_CREATEREPO]
                       name

Alters only specified project property.

--repo::
Repository to add to this project. Can be specified multiple times.

--description::
Description of the project.

--instructions::
Instructions for the project.

--disable_createrepo::
Disables automatic repository metadata generation. Accepted values for DISABLE_CREATEREPO: true/false.


EXIT STATUS
-----------
Normally, the exit code is 0 when everything goes well. But if not, we could get:
1 - Bad request like wrong project name, insufficient rights etc.
    Also might happen when user interrupts the operation when they shouldn't.
2 - Wrong arguments given.
3 - Bad or no configuration.
4 - Build fails when Cli is waiting for the result.
5 - Communication error between Cli and server.
    This issue probably means bug and should be reported.


API KEY
-------

Visit the page https://copr.fedoraproject.org/api/ to obtain an API token.
This token must be saved in the file `~/.config/copr` in the following
format:

 [copr-cli]
 username = msuchy
 login = Y57wcg==##fkfaxbkjhuoiebfafadl
 token = vbfseelqdebzedukgombekmuvbkqwo

Be aware that API tokens have an expiration date. The expiration date for
your token is listed on the /api page.

If you are using a different instance for the Copr service, the API token is
available from http://your.copr.server/api/

COPR URL
--------

You can alternatively specify a different URL for the Copr service.
Open the file `~/.config/copr` provide the `copr_url` setting:

 [copr-cli]
 copr_url = https://copr.fedoraproject.org

The value listed above is the default value. Only define copr_url only if
you use a different instance.

AUTHORS
-------
Miroslav Suchý <msuchy@redhat.com>
