"""add_legal_flag

Revision ID: 246fd2dbf398
Revises: d062c3d9c00
Create Date: 2013-04-03 10:39:54.837803

"""

# revision identifiers, used by Alembic.
revision = '246fd2dbf398'
down_revision = 'd062c3d9c00'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('legal_flag', sa.Column('resolved_on', sa.Integer(), nullable=True))
    op.add_column('legal_flag', sa.Column('raised_on', sa.Integer(), nullable=True))
    op.drop_column('legal_flag', u'state')
    op.drop_column('legal_flag', u'resolve_message')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('legal_flag', sa.Column(u'resolve_message', sa.TEXT(), nullable=True))
    op.add_column('legal_flag', sa.Column(u'state', sa.INTEGER(), nullable=True))
    op.drop_column('legal_flag', 'raised_on')
    op.drop_column('legal_flag', 'resolved_on')
    ### end Alembic commands ###
