"""empty message

Revision ID: 2fa80e062525
Revises: 2e30169e58ce
Create Date: 2013-01-14 09:04:42.768432

"""

# revision identifiers, used by Alembic.
revision = '2fa80e062525'
down_revision = '2e30169e58ce'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mock_chroot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('os_release', sa.String(length=50), nullable=False),
    sa.Column('os_version', sa.String(length=50), nullable=False),
    sa.Column('arch', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('copr_chroot',
    sa.Column('mock_chroot_id', sa.Integer(), nullable=False),
    sa.Column('copr_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['copr_id'], ['copr.id'], ),
    sa.ForeignKeyConstraint(['mock_chroot_id'], ['mock_chroot.id'], ),
    sa.PrimaryKeyConstraint('mock_chroot_id', 'copr_id')
    )
    if op.get_bind().dialect.name == 'sqlite':
        op.rename_table('copr', 'copr_1')
        op.create_table('copr',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('repos', sa.Text(), nullable=True),
        sa.Column('created_on', sa.Integer(), nullable=True),
        sa.Column('build_count', sa.Integer(), nullable=True),
        sa.Column('owner_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.execute('INSERT INTO copr SELECT id,name,repos,created_on,build_count,owner_id FROM copr_1')
        op.drop_table('copr_1')
    else:
        op.drop_column('copr', u'chroots')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('copr', sa.Column(u'chroots', sa.TEXT(), nullable=False))
    op.drop_table('copr_chroot')
    op.drop_table('mock_chroot')
    ### end Alembic commands ###
