"""empty message

Revision ID: 2fa80e062525
Revises: 2e30169e58ce
Create Date: 2013-01-14 09:04:42.768432

"""

# revision identifiers, used by Alembic.
revision = '2fa80e062525'
down_revision = '2e30169e58ce'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mock_chroot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('os_release', sa.String(length=50), nullable=False),
    sa.Column('os_version', sa.String(length=50), nullable=False),
    sa.Column('arch', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('copr_chroot',
    sa.Column('mock_chroot_id', sa.Integer(), nullable=False),
    sa.Column('copr_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['copr_id'], ['copr.id'], ),
    sa.ForeignKeyConstraint(['mock_chroot_id'], ['mock_chroot.id'], ),
    sa.PrimaryKeyConstraint('mock_chroot_id', 'copr_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('copr_chroot')
    op.drop_table('mock_chroot')
    ### end Alembic commands ###
