"""generalize_action

Revision ID: 451e9507b866
Revises: 2a75f0a06d90
Create Date: 2013-03-29 12:13:33.303584

"""

# revision identifiers, used by Alembic.
revision = '451e9507b866'
down_revision = '2a75f0a06d90'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('action', sa.Column('message', sa.Text(), nullable=True))
    op.add_column('action', sa.Column('ended_on', sa.Integer(), nullable=True))
    op.drop_column('action', u'backend_message')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('action', sa.Column(u'backend_message', sa.TEXT(), nullable=True))
    op.drop_column('action', 'ended_on')
    op.drop_column('action', 'message')
    ### end Alembic commands ###
