"""empty message

Revision ID: 544873aa3ba1
Revises: 1ee4b45f5476
Create Date: 2013-02-20 13:20:34.778470

"""

# revision identifiers, used by Alembic.
revision = "544873aa3ba1"
down_revision = "1ee4b45f5476"

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table("action",
                    sa.Column("id", sa.Integer(), nullable=False),
                    sa.Column("action_type", sa.Integer(), nullable=False),
                    sa.Column(
                        "object_type", sa.String(length=20), nullable=True),
                    sa.Column("object_id", sa.Integer(), nullable=True),
                    sa.Column(
                        "old_value", sa.String(length=255), nullable=True),
                    sa.Column(
                        "new_value", sa.String(length=255), nullable=True),
                    sa.Column("backend_result", sa.Integer(), nullable=True),
                    sa.Column("backend_message", sa.Text(), nullable=True),
                    sa.Column("created_on", sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint("id")
                    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("action")
    ### end Alembic commands ###
