copr-rpmbuild(1)
================

NAME
----
copr-rpmbuild - run COPR builds

SYNOPSIS
--------
*copr-rpmbuild* [*-c*|*--config* _CONFIG_PATH_] [*-d*|*--detached*] [*--drop-resultdir*] [*--rpm*|*--srpm*] [*-r*|*--chroot* _CHROOT_NAME_] [*-v*|*--verbose*] [*-h*|*--help*] [*--build-id* _COPR_BUILD_ID_]

DESCRIPTION
-----------
Runs COPR build of the specified build ID and puts
results into _/var/lib/copr-rpmbuild/results/_. The
script generates target RPMs by default but it can
also generate just an SRPM by using *--srpm* switch.

OPTIONS
-------
*--build-id* _COPR_BUILD_ID_::
    Run build of the specified ID.

*--drop-resultdir*::
    Drops resultdir and its content at the beginning before continuing.

*-c*, *--config* _CONFIG_PATH_::
    Path to an alternative config file. By default _/etc/copr-rpmbuild/main.ini_ is used.

*-d*, *--detached*::
    Run build in background and output the process PID. Log into _/var/lib/copr-rpmbuild/main.log_.

*-r*, *--chroot* _CHROOT_NAME_::
    Name of the chroot to build for. This follows mock's convention for naming chroots (e.g. fedora-27-x86_64). See _/etc/mock_ for the full list.

*--srpm*::
    Build SRPM instead of building RPM.

*--rpm*::
    Build RPM. This is the default action. Requires *--chroot* to be specified.

*-v*, *--verbose*::
    Print debugging information.

*-h*, *--help*::
    Display help.


EXAMPLES
--------
copr-rpmbuild -v --build-id 551347 --chroot epel-7-x86_64::
    Runs COPR build of ID 551347 in epel-7-x86_64 mock chroot and print verbose information. RPM will be the result.

copr-rpmbuild -v --build-id 551347 --srpm::
    Runs the same COPR build as in the previous example and again with verbose information but this time, SRPM will be built.

AUTHORS
-------

clime <clime@redhat.com>

Jakub Kadlcik <jkadlcik@redhat.com>
