FROM copr-base:latest

LABEL description="COPR Backend services"

ENV PYTHONPATH=/usr/share/copr/

RUN --mount=type=cache,target=/var/cache/dnf \
    dnf -y install \
        copr-backend \
        expect \
        git \
        iputils \
        openssh-server \
        psmisc \
        pulp-cli \
        resalloc \
        rng-tools \
        sudo \
    && dnf clean all

RUN set -ex && \
    setcap cap_net_raw,cap_net_admin+p /usr/bin/ping && \
    ssh-keygen -f /etc/ssh/ssh_host_rsa_key -N '' -q && \
    echo 'root:passwd' | chpasswd && \
    chmod 700 /root /root/.ssh && \
    echo 'copr:passwd' | chpasswd && \
    echo 'copr ALL=(ALL:ALL) NOPASSWD:ALL' >> /etc/sudoers && \
    mkdir -p /home/copr/.ssh && \
    chmod 700 /home/copr /home/copr/.ssh && \
    ssh-keygen -f /home/copr/.ssh/id_rsa -N '' -q -C copr@localhost && \
    touch /home/copr/.ssh/authorized_keys && \
    chmod 600 /home/copr/.ssh/authorized_keys && \
    cat /home/copr/.ssh/id_rsa.pub >> /root/.ssh/authorized_keys && \
    cat /home/copr/.ssh/id_rsa.pub >> /home/copr/.ssh/authorized_keys && \
    chown -R copr:copr /home/copr && \
    usermod -a -G mock copr && \
    mkdir -p /var/lock/copr-backend && \
    chown copr:copr /var/lock/copr-backend && \
    rngd -r /dev/urandom || true

COPY files/ /

RUN set -ex && \
    chmod 700 /root /home/copr && \
    chmod 400 /home/copr/.ssh/id_rsa && \
    chmod 600 /home/copr/.ssh/id_rsa.pub && \
    chown -R copr:copr /home/copr && \
    chmod 0755 /usr/bin/sign && \
    chown copr:root /etc/sign.conf && \
    chmod 0660 /etc/sign.conf

USER copr
CMD ["/run-backend"]
