%global date %(date '+%a %b %d %Y')

Name:		%{username}-%{projectname}
Version:	1
Release:	1%{?dist}
Summary:	%{username}-%{projectname} yum repository

Group:		System Environment/Base
License:	WTFPL
URL:		http://copr.fedoraproject.org/coprs/%{username}/%{projectname}
BuildArch:	noarch

# whatever provides /etc/yum.repos.d/
Requires:   system-release

%description
%{copr_description}

%prep
#nothing to do here

%build
cat <<EOF >%{username}-%{projectname}.repo
[%{username}-%{projectname}]
name=Copr repo for %{projectname} owned by %{username}
description=%{copr_description}
baseurl=%{baseurl}
skip_if_unavailable=True
gpgcheck=0
enabled=1
EOF

%install
mkdir -p %{buildroot}%{_sysconfdir}/yum.repos.d
cp %{username}-%{projectname}.repo %{buildroot}%{_sysconfdir}/yum.repos.d

%files
%{_sysconfdir}/yum.repos.d/%{username}-%{projectname}.repo


%changelog
* %{date} Copr build system - %{version}-%{release}
- automaticaly generated by Copr
