---
- name: Fetch the fe-be key from the credentials host
  ansible.builtin.slurp:
    src: /root/be-fe-token
  delegate_to: "{{ host_with_secrets }}"
  register: be_fe_token

- name: Configure Copr Backend
  ansible.builtin.template:
    src: copr-be.conf.j2
    dest: /etc/copr/copr-be.conf
    owner: copr
    group: copr
    mode: '0600'
  notify: restart copr-backend

- name: Deploy Copr Backend HTTPD Configuration
  ansible.builtin.template:
    # Source template path (relative to the role's 'templates/' directory)
    src: httpd-copr-be.conf.j2
    # Destination path on the remote host (uses an absolute path)
    dest: /etc/httpd/conf.d/copr-backend.conf
    # Set standard ownership and read permissions
    owner: root
    group: root
    mode: '0644'
  notify: restart httpd

- name: "install copr → builder ssh config"
  ansible.builtin.copy:
    content: |
      Host *
        StrictHostKeyChecking no
        UserKnownHostsFile /dev/null
        ServerAliveInterval 20
        ServerAliveCountMax 5
        ConnectTimeout 60
    dest: "/copr-to-builder-ssh-config"
    owner: copr
    group: copr
    mode: '0600'

- name: Fetch the Backend->Builder SSH private key
  ansible.builtin.slurp:
    src: /root/backend_builder
  delegate_to: "{{ host_with_secrets }}"
  register: key_file

- name: Install the fetched SSH private key
  ansible.builtin.copy:
    content: "{{ key_file['content'] | b64decode }}"
    dest: "/var/lib/resallocserver/.ssh/id_ed25519"
    owner: resalloc
    group: resalloc
    mode: '0600'

- name: Fetch the Backend->Builder SSH public key
  ansible.builtin.slurp:
    src: /root/backend_builder.pub
  delegate_to: "{{ host_with_secrets }}"
  register: key_file

- name: Install the fetched SSH public key
  ansible.builtin.copy:
    content: "{{ key_file['content'] | b64decode }}"
    dest: "{{ resalloc_image_dir }}/key.pub"
    owner: resalloc
    group: resalloc
    mode: '0600'
