#! /bin/sh

# This file contains all the _mandatory_ Copr frontend tasks to be executed
# daily.  Don't edit this file manually, it is automatically updated with
# copr-frontend.rpm.

runuser -c '/usr/share/copr/coprs_frontend/manage.py vacuum-graphs' - copr-fe
runuser -c '/usr/share/copr/coprs_frontend/manage.py clean-expired-projects' - copr-fe
runuser -c '/usr/share/copr/coprs_frontend/manage.py clean-old-builds' - copr-fe
runuser -c '/usr/share/copr/coprs_frontend/manage.py delete-dirs' - copr-fe
