FROM copr-base:latest

LABEL description="COPR Resalloc - resource allocation service"

RUN --mount=type=cache,target=/var/cache/dnf \
    dnf -y install \
        ansible \
        openssh-clients \
        resalloc \
        resalloc-aws \
        resalloc-server \
        resalloc-webui \
        sqlite \
    && dnf clean all

COPY files/ /

RUN mkdir -p /persistent && \
    chown -R resalloc:resalloc /persistent

USER resalloc
EXPOSE 49100 5000
ENTRYPOINT []
CMD bash -c 'cd $(rpm -ql resalloc-server | grep alembic.ini | xargs dirname) && alembic-3 upgrade head && /usr/bin/resalloc-server'
