#!/bin/bash

export SCRIPTDIR="$(builtin cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source $SCRIPTDIR/lib.sh

PROJECT=$1
if [ -z "$PROJECT" ]; then
	echo "usage: build-packages project"
    echo "       where TARGET is either @copr/copr or @copr/copr-dev"
    exit 1
fi

for package in $(get_all_packages); do
    echo "##############################"
    echo "Building $(basename $package):"
    echo "##############################"
    pushd $package >/dev/null
    rpkg build $PROJECT
    popd >/dev/null
    echo
done
