#! /bin/bash -e

info() { echo "INFO: $*" >&2 ; }

: "${PYTHON_PKG_SUFFIX=}"

# By default we check against `origin/main`.  This is the case also in GH Action
# for pull-requests that submits builds and detects changed packages (we are
# checked-out into the `merged` branch on top of main).
#
# If we want to diff against the BASE of a PR (without merge commit), we have to
# export PULL_REQUEST_ID env var.  This is the testing-farm case.
#
# If we run this in GH Action for push event, we have the COMMIT_SHA to diff
# against.

curl=(curl --location --connect-timeout 60 --retry 5 --retry-delay 20 --remote-time --show-error --fail)
diff_against=origin/main
if test -n "$COMMIT_SHA"; then
    info "Diffing against given commit: $COMMIT_SHA"
    diff_against=$COMMIT_SHA
elif test -n "$PULL_REQUEST_ID"; then
    info "Checking the base commit for PR $PULL_REQUEST_ID"
    diff_against=$("${curl[@]}" "https://api.github.com/repos/fedora-copr/copr/pulls/$PULL_REQUEST_ID" | jq -r '.base.sha')
fi

info "Diffing against $diff_against"

cd "$(git rev-parse --show-toplevel)"

git diff --name-status -C "$diff_against" --numstat | cut -f2 | sed 's|/.*||' \
| sort | uniq | while read -r line; do
    case $line in
        backend|frontend|cli|keygen|dist-git|messaging|rpmbuild|selinux)
            echo "copr-$line"
            ;;
        python)
            echo "python$PYTHON_PKG_SUFFIX-copr"
            ;;
        common)
            echo "python$PYTHON_PKG_SUFFIX-copr-common"
            ;;
    esac
done
