#!/bin/bash

export SCRIPTDIR="$(builtin cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source $SCRIPTDIR/lib.sh

function filter_tags {
    grep -E "^$1-[^-]+-[^-]+$"
}

for package in $(get_all_packages); do
    cd $package

    nvr="$(rpkg -q verrel 2>/dev/null)"
    name="$(echo $nvr | sed -E -n "s/^(.*)-[^-]+-[^-]+$/\1/p")"

    mapfile -t tags < <(git tag --list --sort=taggerdate:unix "$name*" --merged 2>/dev/null | filter_tags "$name")

    if [ ${#tags[@]} -gt 0 ]; then
        revexpr="${tags[-1]}..HEAD"
    else
        revexpr="HEAD"
    fi

    log=$(git log --pretty=format:'%h %s (%ae)' $revexpr -- $package)
    if [ -z "$log" ]; then
        continue
    fi

    echo "Listing $revexpr for package $name:"
    echo "------------------------------------------------------------"
    echo "$log"
    echo
done
