- name: install pkgs
  yum: state=present pkg={{ item }}
  with_items:
    - dnf
    - mock
    - mock-lvm
    - createrepo
    - yum-utils
    - pyliblzma
    - rsync
    - openssh-clients
    - rsync
    - libselinux-python
    - libsemanage-python

- name: make sure newest rpm
  # todo: replace with dnf after ansible 1.9 is available
  yum: name={{ item }} state=latest
  with_items:
    - rpm
    - glib2
    - ca-certificates

- name: put updated mock configs into /etc/mock
  copy: src=files/mock/{{ item }} dest=/etc/mock
  with_items:
    - site-defaults.cfg

# ansible doesn't support simultaneously usage of async and with_* options
# it's not even planned for implementation, see https://github.com/ansible/ansible/issues/5841
#- name: prepare caches
#  when: prepare_base_image is defined
#  async: 3600
#  command: mock -r {{ item }} --init
#  with_items:
#    - epel-5-i386
#    - epel-5-x86_64
#    - epel-6-i386
#    - epel-6-x86_64
#    - epel-7-x86_64
#    - fedora-20-i386
#    - fedora-20-x86_64
#    - fedora-21-i386
#    - fedora-21-x86_64
#    - fedora-22-i386
#    - fedora-22-x86_64
#    - fedora-rawhide-i386
#    - fedora-rawhide-x86_64


- name: prepare cache
  when: prepare_base_image is defined and prepare_base_image
  async: 3600
  shell: "for i in epel-5-i386 epel-5-x86_64 epel-6-i386 epel-6-x86_64 epel-7-x86_64 fedora-20-i386 fedora-20-x86_64 fedora-21-i386 fedora-21-x86_64 fedora-22-i386 fedora-22-x86_64 fedora-rawhide-i386 fedora-rawhide-x86_64; do mock --init -r $i; done"

- name: mockbuilder user
  user: name=mockbuilder groups=mock

- name: mockbuilder .ssh
  file: state=directory path=/home/mockbuilder/.ssh mode=0700 owner=mockbuilder group=mockbuilder

- name: mockbuilder authorized_keys
  authorized_key: user=mockbuilder key='{{ lookup('file', '/home/copr/provision/files/buildsys.pub') }}'

- name: root authorized_keys
  authorized_key: user=root key='{{ lookup('file', '/home/copr/provision/files/buildsys.pub') }}'

- lineinfile: dest=/etc/mock/fedora-rawhide-x86_64.cfg line="config_opts['package_manager'] = 'dnf'" state=absent
- lineinfile: dest=/etc/mock/fedora-rawhide-i386.cfg line="config_opts['package_manager'] = 'dnf'" state=absent

- lineinfile: dest=/etc/security/limits.conf line="* soft nofile 10240" insertafter=EOF
- lineinfile: dest=/etc/security/limits.conf line="* hard nofile 10240" insertafter=EOF

- name: Disable DNF makecache timer
  systemd:
    name: dnf-makecache.timer
    state: stopped
    enabled: no

- name: Disable DNF makecache service
  systemd:
    name: dnf-makecache.service
    state: stopped
    enabled: no
