#! /usr/bin/python3

import sys
import os
import logging
import getpass
from copr_common.log import setup_script_logger
from copr_keygen.gpg import gpg_cmd

if getpass.getuser() != 'copr-signer':
    sys.stderr.write("run as 'copr-signer' user\n")
    sys.exit(1)


log = logging.getLogger(__name__)
setup_script_logger(log, "/var/log/copr-keygen/gpg-copr.log")


cmd = gpg_cmd + sys.argv[1:]
log.info("Running command: %s", " ".join(cmd))
os.execve(cmd[0], cmd, os.environ)
