---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: copr-frontend
spec:
  template:
    spec:
      containers:
        - name: frontend
          env:
            - name: PUBLIC_COPR_HOSTNAME
              value: "copr-frontend-copr.apps.crc.testing"
            - name: PUBLIC_COPR_BASE_URL
              value: "http://copr-frontend-copr.apps.crc.testing"
            - name: BACKEND_BASE_URL
              value: "http://copr-backend-copr.apps.crc.testing"
            - name: RESALLOC_URL
              value: "http://copr-resalloc-copr.apps.crc.testing"
            - name: DISTGIT_BASE_URL
              value: "http://copr-distgit-copr.apps.crc.testing"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: copr-backend
spec:
  template:
    spec:
      initContainers:
        - name: render-config
          env:
            - name: PUBLIC_BACKEND_URL
              value: "http://copr-backend-copr.apps.crc.testing"
