---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: copr-builder-sa
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: copr-anyuid
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: copr-builder-manager
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create", "delete", "list", "get", "watch"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: copr-builder-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: copr-builder-manager
subjects:
  - kind: ServiceAccount
    name: copr-builder-sa
