---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: copr-frontend
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: frontend
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: copr-backend
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: backend-httpd
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: copr-distgit
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: distgit
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: copr-resalloc
spec:
  port:
    targetPort: webui
  to:
    kind: Service
    name: resalloc
