#! /usr/bin/python3

"""
Process one Build task provided by frontend (on backend).
"""

from copr_backend.background_worker_build import BuildBackgroundWorker

if __name__ == "__main__":
    BuildBackgroundWorker().process()
