#!/bin/sh

# Copr instance
# In some cases it might be useful to use different instance than
# copr-*-dev (e.g. having post-release test for prodution or running
# tests against a local dev stack). For this reason, the following
# settings are override-able from command line.
if [[ ! $FRONTEND_URL ]]; then
    FRONTEND_URL="https://copr-fe-dev.cloud.fedoraproject.org"
fi
if [[ ! $BACKEND_URL ]]; then
    BACKEND_URL="https://copr-be-dev.cloud.fedoraproject.org"
fi


# Owner and project
OWNER="@copr"
NAME_VAR="TEST$(date +%s)" # names should be unique
NAME_PREFIX="$OWNER/$NAME_VAR"
USER=`copr-cli whoami`


# Some tests might want to install built packages
# Therefore, these packages need to be built for the same fedora version
# as this script is going to be run from
FEDORA_VERSION=30
CHROOT="fedora-$FEDORA_VERSION-x86_64"
BRANCH="f$FEDORA_VERSION"


# Useful paths
SCRIPTPATH="$( builtin cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
HERE=$SCRIPTPATH
FILES=$HERE/files


# Debug
echo "USER = $USER"
echo "FRONTEND_URL = $FRONTEND_URL"
echo "BACKEND_URL = $BACKEND_URL"
