#!/bin/sh

HELLO=https://pagure.io/copr/copr-test-sources/raw/master/f/hello-2.8-1.src.rpm
EVIL_HELLO=https://pagure.io/copr/copr-test-sources/raw/master/f/evilhello-2.8-2.src.rpm
COPR_HELLO_GIT=https://pagure.io/copr/copr-hello.git

parse_build_id()
{
   local id
   id=$(grep 'Created builds:' "$rlRun_LOG" | sed 's/.* //')
   test -n "$id" || return 1
   export BUILD_ID=$id
}
