#! /bin/sh

# This file contains all the _mandatory_ Copr frontend tasks to be executed
# hourly.  Don't edit this file manually, it is automatically updated with
# copr-frontend.rpm.

runuser -c '/usr/share/copr/coprs_frontend/manage.py update-indexes-quick 120 &> /dev/null' - copr-fe
runuser -c '/usr/share/copr/coprs_frontend/manage.py update-graphs &> /dev/null' - copr-fe
