---
- name: Copr deployment
  hosts: all
  vars:
    validate_certs: false
    service: copr
    deployment: dev
    sandbox_namespace: "{{ service }}-{{ deployment }}-sandbox"
    project_dir: "{{ playbook_dir }}"
    helm_dir: "{{ project_dir }}/helm"

  vars_files:
    "{{ helm_dir }}/secrets.yaml"

  tasks:
    - name: detect the currently operated OpenShift cluster
      shell: oc config view --minify -o jsonpath='{.clusters[*].cluster.server}'
      register: oc_api_endpoint_detected
      changed_when: false
      tags: always

    - name: check that we work with the right OpenShift cluster
      assert:
        that:
          - oc_api_endpoint_detected.stdout_lines[0] == oc_api_endpoint
        msg: "OpenShift API mismatch"
      tags: always

    - name: detect the OpenShift API key - ARE YOU LOGGED IN?
      command: oc whoami -t
      register: openshift_token_detected
      no_log: true
      changed_when: false
      tags: always

    - name: define the api_key variable
      set_fact:
        api_key: "{{ openshift_token_detected.stdout_lines[0] }}"
      tags: always

    - name: Create the project
      k8s:
        definition: "{{ lookup('template', 'project.yaml.j2') }}"
        api_key: "{{ api_key }}"
        validate_certs: "{{ validate_certs }}"
      tags: always

    - name: Lint Copr Helm chart
      command:
        argv:
          - helm
          - lint
          - "{{ helm_dir }}"
          - --values
          - "{{ helm_dir }}/values.yaml"
          - --values
          - "{{ helm_dir }}/values.communishift.yaml"
          - --values
          - "{{ helm_dir }}/secrets.yaml"
          - --set
          - create_project=false
      tags: always

    - name: Deploy Copr with Helm
      command:
        argv:
          - helm
          - upgrade
          - --install
          - copr
          - "{{ helm_dir }}"
          - --namespace
          - "{{ project }}"
          - --values
          - "{{ helm_dir }}/values.yaml"
          - --values
          - "{{ helm_dir }}/values.communishift.yaml"
          - --values
          - "{{ helm_dir }}/secrets.yaml"
          - --disable-openapi-validation
          - --set
          - create_project=false
      tags: always
