FROM registry.fedoraproject.org/fedora:43
LABEL maintainer="copr-devel@lists.fedorahosted.org"
LABEL description="Redis/Valkey server for COPR"

RUN dnf install -y redis && dnf clean all

RUN mkdir -p /data && chown valkey:valkey /data

EXPOSE 6379

USER valkey
CMD ["redis-server", "--protected-mode", "no", "--dir", "/data"]
